Repository 3I-shikosai32/shikosai32-server, pull requests merged in 2022-09, with the labels that each got.

#37 feat: ✨ Userコンポーネントの雛型を作成
  schema.gql
  src/components/hello/hello.module.ts
  src/components/hello/hello.resolver.query.ts
  src/components/index.ts
  src/components/user/user.module.ts
  src/components/user/user.resolver.mutation.ts
  src/components/user/user.resolver.query.ts
  src/components/user/user.resolver.subscription.ts
  src/components/user/user.service.ts
Labels: ✨新機能

#41 fix: 🐞 @prisma/clientを自動生成し忘れていたため再生成
  src/libs/prisma/generated/gift-history/gift-history-count-aggregate/input.ts
  src/libs/prisma/generated/gift-history/gift-history-count-aggregate/output.ts
  src/libs/prisma/generated/gift-history/gift-history-count-order-by-aggregate/input.ts
  src/libs/prisma/generated/gift-history/gift-history-create-many-exchanged-gift/input.ts
  src/libs/prisma/generated/gift-history/gift-history-create-many-user/input.ts
  src/libs/prisma/generated/gift-history/gift-history-create-many/input.ts
  src/libs/prisma/generated/gift-history/gift-history-create-without-exchanged-gift/input.ts
  src/libs/prisma/generated/gift-history/gift-history-create-without-user/input.ts
  src/libs/prisma/generated/gift-history/gift-history-create/input.ts
  src/libs/prisma/generated/gift-history/gift-history-group-by/output.ts
  src/libs/prisma/generated/gift-history/gift-history-max-aggregate/input.ts
  src/libs/prisma/generated/gift-history/gift-history-max-aggregate/output.ts
  src/libs/prisma/generated/gift-history/gift-history-max-order-by-aggregate/input.ts
  src/libs/prisma/generated/gift-history/gift-history-min-aggregate/input.ts
  src/libs/prisma/generated/gift-history/gift-history-min-aggregate/output.ts
  src/libs/prisma/generated/gift-history/gift-history-min-order-by-aggregate/input.ts
  src/libs/prisma/generated/gift-history/gift-history-order-by-with-aggregation/input.ts
  src/libs/prisma/generated/gift-history/gift-history-order-by-with-relation/input.ts
  src/libs/prisma/generated/gift-history/gift-history-scalar-field/enum.ts
  src/libs/prisma/generated/gift-history/gift-history-scalar-where-with-aggregates/input.ts
  src/libs/prisma/generated/gift-history/gift-history-scalar-where/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-create-without-exchanged-gift/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-create-without-user/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-create/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-update-many-without-gift-histories/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-update-many/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-update-without-exchanged-gift/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-update-without-user/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-update/input.ts
  src/libs/prisma/generated/gift-history/gift-history-update-many-mutation/input.ts
  src/libs/prisma/generated/gift-history/gift-history-update-without-exchanged-gift/input.ts
  src/libs/prisma/generated/gift-history/gift-history-update-without-user/input.ts
  src/libs/prisma/generated/gift-history/gift-history-update/input.ts
  src/libs/prisma/generated/gift-history/gift-history-where/input.ts
  src/libs/prisma/generated/gift-history/gift-history/model.ts
  src/libs/prisma/generated/prisma/bool-with-aggregates-filter/input.ts
  src/libs/prisma/generated/prisma/nested-bool-with-aggregates-filter/input.ts
Labels: 🐛バグ

#42 build: 📦️ prisma及び@prisma/clientをlatestにupgrade
  package.json
  yarn.lock
Labels: 📚ライブラリ

#38 feat: ✨ (UserService) CRUDの処理を行うメソッドを作成
  src/components/user/user.service.ts
Labels: ✨新機能

#50 fix: 🐛 DB Schemaの問題を修正
  src/libs/prisma/generated/user/user-create-many/input.ts
  src/libs/prisma/generated/user/user-create-without-gift-histories/input.ts
  src/libs/prisma/generated/user/user-create/input.ts
  src/libs/prisma/generated/user/user-unchecked-create-without-gift-histories/input.ts
  src/libs/prisma/generated/user/user-unchecked-create/input.ts
  src/libs/prisma/generated/user/user/model.ts
  src/libs/prisma/schema.prisma
Labels: ✨新機能, 🐛バグ

#58 feat: ⚰️ Gift.remainingの@default()を削除
  src/libs/prisma/generated/gift/gift-create-many/input.ts
  src/libs/prisma/generated/gift/gift-create-without-gift-histories/input.ts
  src/libs/prisma/generated/gift/gift-create/input.ts
  src/libs/prisma/generated/gift/gift-unchecked-create-without-gift-histories/input.ts
  src/libs/prisma/generated/gift/gift-unchecked-create/input.ts
  src/libs/prisma/generated/gift/gift/model.ts
  src/libs/prisma/schema.prisma
Labels: 🐛バグ

#57 feat: ✨ 全てのコンポーネントのDTOを作成
  src/components/gift/dto/args/findGift.ts
  src/components/gift/dto/args/findGifts.ts
  src/components/gift/dto/args/updateGift.ts
  src/components/gift/dto/input/order.ts
  src/components/gift/dto/input/relationFilter.ts
  src/components/gift/dto/input/update.ts
  src/components/gift/dto/input/where.ts
  src/components/gift/dto/input/whereUnique.ts
  src/components/gift/dto/object/index.ts
  src/components/gift/dto/object/nested.ts
  src/components/gift_history/dto/args/createGiftHistory.ts
  src/components/gift_history/dto/args/finGiftHistories.ts
  src/components/gift_history/dto/args/findGiftHistory.ts
  src/components/gift_history/dto/args/updateGiftHistory.ts
  src/components/gift_history/dto/input/create.ts
  src/components/gift_history/dto/input/index.ts
  src/components/gift_history/dto/input/listRelationFilter.ts
  src/components/gift_history/dto/input/order.ts
  src/components/gift_history/dto/input/update.ts
  src/components/gift_history/dto/input/where.ts
  src/components/gift_history/dto/input/whereUnique.ts
  src/components/gift_history/dto/object/index.ts
  src/components/gift_history/dto/object/nested.ts
  src/components/user/dto/args/createUser.ts
  src/components/user/dto/args/findUser.ts
  src/components/user/dto/args/findUsers.ts
  src/components/user/dto/args/updateUser.ts
  src/components/user/dto/input/create.ts
  src/components/user/dto/input/order.ts
  src/components/user/dto/input/relationFilter.ts
  src/components/user/dto/input/update.ts
  src/components/user/dto/input/where.ts
  src/components/user/dto/input/whereUnique.ts
  src/components/user/dto/object/index.ts
  src/components/user/dto/object/nested.ts
Labels: ✨新機能

#60 feat: ✨ GiftHistoryの雛型を作成
  src/components/gift_history/gift_history.module.ts
  src/components/gift_history/gift_history.resolver.mutation.ts
  src/components/gift_history/gift_history.resolver.query.ts
  src/components/gift_history/gift_history.resolver.subscription.ts
  src/components/gift_history/gift_history.service.ts
  src/components/index.ts
Labels: ✨新機能

#63 ci: 🦺 Test jobで@prisma/clientが見つからない問題を修正
  .github/workflows/test.yml
Labels: 🐛バグ, 🦺CI

#61 feat: ✨ Giftの雛型を作成
  src/components/gift/gift.module.ts
  src/components/gift/gift.resolver.mutation.ts
  src/components/gift/gift.resolver.query.ts
  src/components/gift/gift.resolver.subscription.ts
  src/components/gift/gift.service.ts
  src/components/index.ts
Labels: ✨新機能

#64 feat: ✨ (UserQuery) findUserById GraphQL Queryを作成
  schema.gql
  src/components/user/user.resolver.query.spec.ts
  src/components/user/user.resolver.query.ts
Labels: ✨新機能, 🧪テスト

#67 feat: ✨ NODE_ENVに応じて環境変数を使い分けられるように修正
  .github/workflows/test.yml
  package.json
  src/config/environment/getter/getter.module.ts
  src/config/graphql/graphql.config.ts
  yarn.lock
Labels: ✨新機能, 🛠設定

#68 test: 🧪 UserService.findUniqueのテストを作成
  .github/workflows/test.yml
  package.json
  src/components/user/user.service.spec.ts
  yarn.lock
Labels: 🧪テスト, 🦺CI

#71 feat: ✨ (schema.prisma) User.idに@default(auto())を再付与
  src/libs/prisma/generated/user/user-create-many/input.ts
  src/libs/prisma/generated/user/user-create-without-gift-histories/input.ts
  src/libs/prisma/generated/user/user-create/input.ts
  src/libs/prisma/generated/user/user-unchecked-create-without-gift-histories/input.ts
  src/libs/prisma/generated/user/user-unchecked-create/input.ts
  src/libs/prisma/schema.prisma
Labels: ✨新機能

#72 test: 🧪 UserServiceでテストされていなかった部分を追加
  src/components/user/user.service.spec.ts
Labels: 🧪テスト

#74 feat: ✨ (GiftService) giftsテーブルへのCRUDを作成
  src/components/gift/gift.service.spec.ts
  src/components/gift/gift.service.ts
  src/components/user/user.service.spec.ts
Labels: ✨新機能, 🧪テスト

#66 feat: ✨ ItemServiceの作成
  src/components/index.ts
  src/components/item/item.module.ts
  src/components/item/item.service.ts
Labels: ✨新機能

#76 feat: ✨ (UserQuery) findUsers GraphQL Queryを作成
  src/components/gift/dto/input/where.ts
  src/components/gift_history/dto/input/where.ts
  src/components/user/dto/input/where.ts
  src/components/user/user.resolver.query.spec.ts
  src/components/user/user.resolver.query.ts
Labels: ✨新機能, 🧪テスト

#75 feat: ✨ (GiftHistoryService) gift_historiesテーブルへのCRUDの処理を作成
  src/components/gift/gift.service.spec.ts
  src/components/gift_history/gift_history.service.spec.ts
  src/components/gift_history/gift_history.service.ts
  src/components/user/user.service.spec.ts
Labels: ✨新機能, 🧪テスト

#84 fix: 🐛 @prisma/clientのenumとprisma-nestjs-graphqlのenumが一致しないバグを修正
  src/components/item/dto/object/index.ts
  src/components/item/dto/object/nested.ts
  src/components/user/dto/input/create.ts
  src/components/user/dto/input/update.ts
  src/components/user/dto/object/index.ts
  src/components/user/dto/object/nested.ts
Labels: 🐛バグ

#87 feat: ✨ (UserMutation) pullGacha GraphQL Mutationを作成
  src/components/gift_history/gift_history.service.spec.ts
  src/components/index.ts
  src/components/item/dto/object/index.ts
  src/components/item/item.service.ts
  src/components/user/dto/args/pullGacha.ts
  src/components/user/user.module.ts
  src/components/user/user.resolver.mutation.spec.ts
  src/components/user/user.resolver.mutation.ts
Labels: ✨新機能, 🧪テスト

#82 fix: 🐞 (GiftSubscription) タイポを修正
  src/components/gift/gift.resolver.subscription.ts
Labels: 🐛バグ

#90 fix: 🐛 同時に複数のCIを走らせると失敗するバグを修正
  src/components/gift/gift.service.spec.ts
  src/components/user/user.service.spec.ts
Labels: 🐛バグ, 🧪テスト

#91 feat: ✨ (UserMutation) createUser GraphQL Mutationを作成
  src/components/user/dto/input/create.ts
  src/components/user/user.resolver.mutation.spec.ts
  src/components/user/user.resolver.mutation.ts
Labels: ✨新機能, 🧪テスト

#93 fix: 🚑️ GraphQL Schemaを自動生成できないバグを修正
  src/components/gift_history/dto/input/create.ts
  src/components/item/dto/object/nested.ts
  src/components/user/dto/input/create.ts
Labels: 🐛バグ, 🚑重大な問題

#94 test: 🧪 (Item Service Test) ItemServiceのテストを作成
  src/components/item/item.service.spec.ts
Labels: 🧪テスト

#96 feat: ✨ (UserMutation) updateUser GraphQL Mutationを作成
  src/components/user/user.resolver.mutation.spec.ts
  src/components/user/user.resolver.mutation.ts
Labels: ✨新機能, 🧪テスト

#97 fix: 🐛 (UserMutation) createUserのGraphQL上の戻り値の型を修正
  src/components/user/user.resolver.mutation.ts
Labels: 🐛バグ

#101 refactor: ♻️ テストコードの変数名を修正
  src/components/gift/gift.service.spec.ts
  src/components/gift_history/gift_history.service.spec.ts
  src/components/item/item.service.spec.ts
  src/components/user/dto/args/incrementTotalPoint.ts
  src/components/user/user.resolver.mutation.spec.ts
  src/components/user/user.resolver.mutation.ts
  src/components/user/user.resolver.query.spec.ts
  src/components/user/user.service.spec.ts
Labels: ♻リファクタリング, 🧪テスト

#100 feat: ✨ (UserMutation) incrementTotalPoint GraphQL Mutationを作成
  src/components/user/dto/args/incrementTotalPoint.ts
  src/components/user/user.resolver.mutation.spec.ts
  src/components/user/user.resolver.mutation.ts
Labels: ✨新機能, 🧪テスト

#103 feat: ✨ (UserMutation) joinGame GraphQL Mutationを作成
  src/components/user/dto/args/joinGame.ts
  src/components/user/user.resolver.mutation.spec.ts
  src/components/user/user.resolver.mutation.ts
Labels: ✨新機能, 🧪テスト

#104 refactor: ♻️ 余剰プロパティによる潜在的な脆弱性を解消
  src/components/gift/gift.service.ts
  src/components/gift_history/gift_history.service.ts
  src/components/item/item.service.ts
  src/components/user/user.resolver.mutation.ts
  src/components/user/user.service.ts
  src/types/strictPropertyCheck.ts
Labels: ♻リファクタリング

#105 feat: ✨ (UserMutation) exitGame GraphQL Mutationを作成
  src/components/user/dto/args/exitGame.ts
  src/components/user/user.resolver.mutation.spec.ts
  src/components/user/user.resolver.mutation.ts
Labels: ✨新機能, 🧪テスト

#120 feat: ✨ (GiftHistoryQuery) findGiftHistories GraphQL Queryを作成
  src/components/gift_history/gift_history.resolver.query.spec.ts
  src/components/gift_history/gift_history.resolver.query.ts
Labels: ✨新機能, 🧪テスト

#119 feat: ✨ (GiftHistoryQuery) findGiftHistory GraphQL Queryを作成
  src/components/gift_history/gift_history.resolver.query.spec.ts
  src/components/gift_history/gift_history.resolver.query.ts
Labels: ✨新機能, 🧪テスト

#118 feat: ✨ (GiftQuery) findGifts GraphQL Queryを作成
  src/components/gift/gift.resolver.query.spec.ts
  src/components/gift/gift.resolver.query.ts
Labels: ✨新機能, 🧪テスト

#117 feat: ✨ (GiftQuery) findGift GraphQL Queryを作成
  src/components/gift/gift.resolver.query.spec.ts
  src/components/gift/gift.resolver.query.ts
Labels: ✨新機能, 🧪テスト

#116 feat: ✨ (GiftHistoryMutation) exchangeGift GraphQL Mutationを作成
  src/components/gift_history/dto/args/exchangeGift.ts
  src/components/gift_history/gift_history.resolver.mutation.spec.ts
  src/components/gift_history/gift_history.resolver.mutation.ts
  src/components/user/user.resolver.mutation.ts
Labels: ✨新機能, 🧪テスト

#122 fix: 🐛 (GiftHistoryModule) DIのバグを修正
  src/components/gift_history/gift_history.module.ts
Labels: 🐛バグ

#123 feat: ⚰️ GiftNameを廃止し、Gift.nameをstring型に変更
  src/components/gift/dto/input/where.ts
  src/components/gift/gift.resolver.query.spec.ts
  src/components/gift/gift.service.spec.ts
  src/components/gift_history/gift_history.resolver.mutation.spec.ts
  src/components/gift_history/gift_history.resolver.query.spec.ts
  src/libs/prisma/generated/gift/gift-create-many/input.ts
  src/libs/prisma/generated/gift/gift-create-without-gift-histories/input.ts
  src/libs/prisma/generated/gift/gift-create/input.ts
  src/libs/prisma/generated/gift/gift-group-by/output.ts
  src/libs/prisma/generated/gift/gift-max-aggregate/output.ts
  src/libs/prisma/generated/gift/gift-min-aggregate/output.ts
  src/libs/prisma/generated/gift/gift-scalar-where-with-aggregates/input.ts
  src/libs/prisma/generated/gift/gift-unchecked-create-without-gift-histories/input.ts
  src/libs/prisma/generated/gift/gift-unchecked-create/input.ts
  src/libs/prisma/generated/gift/gift-unchecked-update-many/input.ts
  src/libs/prisma/generated/gift/gift-unchecked-update-without-gift-histories/input.ts
  src/libs/prisma/generated/gift/gift-unchecked-update/input.ts
  src/libs/prisma/generated/gift/gift-update-many-mutation/input.ts
  src/libs/prisma/generated/gift/gift-update-without-gift-histories/input.ts
  src/libs/prisma/generated/gift/gift-update/input.ts
  src/libs/prisma/generated/gift/gift-where/input.ts
  src/libs/prisma/generated/gift/gift/model.ts
  src/libs/prisma/generated/prisma/enum-gift-name-filter/input.ts
  src/libs/prisma/generated/prisma/enum-gift-name-with-aggregates-filter/input.ts
  src/libs/prisma/generated/prisma/gift-name/enum.ts
  src/libs/prisma/generated/prisma/nested-enum-gift-name-filter/input.ts
  src/libs/prisma/generated/prisma/nested-enum-gift-name-with-aggregates-filter/input.ts
  src/libs/prisma/schema.prisma
Labels: ♻リファクタリング

#125 feat: ✨ (AuthGuard) 開発環境のときはAuthGuardを適用しないように修正
  package.json
  src/guards/auth.guard.ts
Labels: ✨新機能

#129 feat: ✨ (incrementPoint) 複数ユーザーのポイントを一度のクエリで変更できるように修正
  src/components/user/dto/args/incrementPoint.ts
  src/components/user/dto/args/incrementTotalPoint.ts
  src/components/user/dto/input/incrementPoint.ts
  src/components/user/user.resolver.mutation.spec.ts
  src/components/user/user.resolver.mutation.ts
Labels: ✨新機能

#132 feat: ✨ GiftHistoryにdeliveredAtフィールドを追加
  src/components/gift_history/dto/input/index.ts
  src/components/gift_history/dto/input/order.ts
  src/components/gift_history/dto/input/update.ts
  src/components/gift_history/dto/object/index.ts
  src/components/gift_history/dto/object/nested.ts
  src/components/gift_history/gift_history.resolver.mutation.spec.ts
  src/components/gift_history/gift_history.resolver.query.spec.ts
  src/libs/prisma/generated/gift-history/gift-history-count-aggregate/input.ts
  src/libs/prisma/generated/gift-history/gift-history-count-aggregate/output.ts
  src/libs/prisma/generated/gift-history/gift-history-count-order-by-aggregate/input.ts
  src/libs/prisma/generated/gift-history/gift-history-create-many-exchanged-gift/input.ts
  src/libs/prisma/generated/gift-history/gift-history-create-many-user/input.ts
  src/libs/prisma/generated/gift-history/gift-history-create-many/input.ts
  src/libs/prisma/generated/gift-history/gift-history-create-without-exchanged-gift/input.ts
  src/libs/prisma/generated/gift-history/gift-history-create-without-user/input.ts
  src/libs/prisma/generated/gift-history/gift-history-create/input.ts
  src/libs/prisma/generated/gift-history/gift-history-group-by/output.ts
  src/libs/prisma/generated/gift-history/gift-history-max-aggregate/input.ts
  src/libs/prisma/generated/gift-history/gift-history-max-aggregate/output.ts
  src/libs/prisma/generated/gift-history/gift-history-max-order-by-aggregate/input.ts
  src/libs/prisma/generated/gift-history/gift-history-min-aggregate/input.ts
  src/libs/prisma/generated/gift-history/gift-history-min-aggregate/output.ts
  src/libs/prisma/generated/gift-history/gift-history-min-order-by-aggregate/input.ts
  src/libs/prisma/generated/gift-history/gift-history-order-by-with-aggregation/input.ts
  src/libs/prisma/generated/gift-history/gift-history-order-by-with-relation/input.ts
  src/libs/prisma/generated/gift-history/gift-history-scalar-field/enum.ts
  src/libs/prisma/generated/gift-history/gift-history-scalar-where-with-aggregates/input.ts
  src/libs/prisma/generated/gift-history/gift-history-scalar-where/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-create-without-exchanged-gift/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-create-without-user/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-create/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-update-many-without-gift-histories/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-update-many/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-update-without-exchanged-gift/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-update-without-user/input.ts
  src/libs/prisma/generated/gift-history/gift-history-unchecked-update/input.ts
  src/libs/prisma/generated/gift-history/gift-history-update-many-mutation/input.ts
  src/libs/prisma/generated/gift-history/gift-history-update-without-exchanged-gift/input.ts
  src/libs/prisma/generated/gift-history/gift-history-update-without-user/input.ts
  src/libs/prisma/generated/gift-history/gift-history-update/input.ts
  src/libs/prisma/generated/gift-history/gift-history-where/input.ts
  src/libs/prisma/generated/gift-history/gift-history/model.ts
  src/libs/prisma/generated/prisma/date-time-nullable-filter/input.ts
  src/libs/prisma/generated/prisma/date-time-nullable-with-aggregates-filter/input.ts
  src/libs/prisma/generated/prisma/nested-date-time-nullable-filter/input.ts
  src/libs/prisma/generated/prisma/nested-date-time-nullable-with-aggregates-filter/input.ts
  src/libs/prisma/generated/prisma/nested-int-nullable-filter/input.ts
  src/libs/prisma/schema.prisma
Labels: ✨新機能

#134 feat: ⚰️ メソッドが定義されていない不要なResolverを削除
  src/components/gift/gift.module.ts
  src/components/gift/gift.resolver.mutation.ts
  src/components/gift/gift.resolver.subscription.ts
  src/components/gift_history/gift_history.module.ts
  src/components/gift_history/gift_history.resolver.subscription.ts
Labels: ♻リファクタリング, ⚰機能削除

#133 feat: ✨ User.roleがADMIN以外のユーザーを弾くRoleGuardを作成
  src/components/user/user.resolver.mutation.ts
  src/guards/role.guard.ts
Labels: ✨新機能

#136 fix: 🐛 (UserIncrementPointInput) 起動時にGraphQL型を決定できないバグを修正
  src/components/user/dto/input/incrementPoint.ts
Labels: 🐛バグ

#137 feat: ✨ (GiftHistoryMutation) updateGiftHistory GraphQL Mutationを作成
  src/components/gift_history/dto/input/update.ts
  src/components/gift_history/gift_history.resolver.mutation.spec.ts
  src/components/gift_history/gift_history.resolver.mutation.ts
Labels: ✨新機能, 🧪テスト

#141 feat: ✨ (UserMutation.incrementPoint) pullableGachaTimesの加算処理を追加
  src/components/user/user.resolver.mutation.ts
Labels: ✨新機能

#143 fix: 🐞 (UserUpdateInput) 変更時に特別な処理を必要とするフィールドを削除
  src/components/user/dto/input/update.ts
  src/components/user/user.resolver.mutation.ts
Labels: ♻リファクタリング

#140 feat: ✨ updatedGameAttenders GraphQL Subscriptionを作成
  src/components/user/dto/object/gameAttenders.ts
  src/components/user/user.resolver.mutation.spec.ts
  src/components/user/user.resolver.mutation.ts
  src/components/user/user.resolver.subscription.ts
Labels: ✨新機能

#151 refactor: ♻️ `Nested`モデルを廃止し、NestJSの`@ResolveField`を利用するように修正
  src/common/constant/injection-token.constant.ts
  src/module/gift-history/controller/dto/object/gift-history.object.ts
  src/module/gift-history/controller/dto/object/nested-gift-history.object.ts
  src/module/gift-history/controller/gift-history-mutation.resolver.ts
  src/module/gift-history/controller/gift-history-query.resolver.ts
  src/module/gift-history/controller/gift-history.resolver.ts
  src/module/gift-history/domain/model/gift-history.model.ts
  src/module/gift-history/domain/model/nested-gift-history.model.ts
  src/module/gift-history/domain/service/repository/gift-history.repository.ts
  src/module/gift-history/domain/service/use-case/gift-history-reader.use-case.ts
  src/module/gift-history/gift-history.module.ts
  src/module/gift-history/repository/gift-history.repository.spec.ts
  src/module/gift-history/repository/gift-history.repository.ts
  src/module/gift-history/repository/mocked-gift-history.repository.ts
  src/module/gift-history/use-case/gift-history-creator.use-case.ts
  src/module/gift-history/use-case/gift-history-reader.use-case.spec.ts
  src/module/gift-history/use-case/gift-history-reader.use-case.ts
  src/module/gift-history/use-case/gift-history-updater.use-case.ts
  src/module/gift/controller/dto/object/gift.object.ts
  src/module/gift/controller/dto/object/nested-gift.object.ts
  src/module/gift/controller/gift-query.resolver.ts
  src/module/gift/controller/gift.resolver.ts
  src/module/gift/domain/model/gift.model.ts
  src/module/gift/domain/model/nested-gift.model.ts
  src/module/gift/domain/service/repository/gift.repository.ts
  src/module/gift/domain/service/use-case/gift-reader.use-case.ts
  src/module/gift/gift.module.ts
  src/module/gift/repository/gift.repository.spec.ts
  src/module/gift/repository/gift.repository.ts
  src/module/gift/repository/mocked-gift.repository.ts
  src/module/gift/use-case/gift-reader.use-case.spec.ts
  src/module/gift/use-case/gift-reader.use-case.ts
  src/module/item/controller/dto/object/item.object.ts
  src/module/item/controller/dto/object/nested-item.object.ts
  src/module/item/controller/item.resolver.ts
  src/module/item/domain/model/item.model.ts
  src/module/item/domain/model/nested-item.model.ts
  src/module/item/domain/service/repository/item.repository.ts
  src/module/item/domain/service/use-case/item-reader.use-case.ts
  src/module/item/item.module.ts
  src/module/item/repository/item.repository.spec.ts
  src/module/item/repository/item.repository.ts
  src/module/item/repository/mocked-item.repository.ts
  src/module/item/use-case/item-reader.use-case.spec.ts
  src/module/item/use-case/item-reader.use-case.ts
  src/module/user/controller/dto/object/nested-user.object.ts
  src/module/user/controller/dto/object/user.object.ts
  src/module/user/controller/user-mutation.resolver.ts
  src/module/user/controller/user-query.resolver.ts
  src/module/user/controller/user.resolver.ts
  src/module/user/domain/model/nested-user.model.ts
  src/module/user/domain/model/user.model.ts
  src/module/user/domain/service/repository/user.repository.ts
  src/module/user/domain/service/use-case/user-reader.use-case.ts
  src/module/user/repository/mocked-user.repository.ts
  src/module/user/repository/user.repository.spec.ts
  src/module/user/repository/user.repository.ts
  src/module/user/use-case/user-reader.use-case.spec.ts
  src/module/user/use-case/user-reader.use-case.ts
  src/module/user/user.module.ts
Labels: ♻リファクタリング

#177 feat: ⚰️ カスタムロガーを削除し、デフォルトで提供されているものに置換
  src/app/app.module.ts
  src/config/logger/logger.config.json
  src/config/logger/logger.middleware.ts
  src/config/logger/logger.module.ts
  src/config/logger/logger.service.ts
  src/main.ts
  src/module/gift-history/controller/gift-history-mutation.resolver.ts
  src/module/gift-history/controller/gift-history-query.resolver.ts
  src/module/gift/controller/gift-query.resolver.ts
  src/module/user/controller/user-mutation.resolver.ts
  src/module/user/controller/user-query.resolver.ts
Labels: ⚰機能削除

#179 feat: ✨ DataLoaderを実装
  package.json
  src/app/app.module.ts
  src/cache/cache.module.ts
  src/cache/dataloader-cache.service.ts
  src/common/constant/injection-token.constant.ts
  src/common/dataloader/base.dataloader.ts
  src/config/graphql/graphql-config.module.ts
  src/module/gift-history/controller/gift-history.resolver.ts
  src/module/gift-history/gift-history.module.ts
  src/module/gift/controller/gift-query.resolver.ts
  src/module/gift/controller/gift.resolver.ts
  src/module/gift/dataloader/gift-gift-histories.dataloader.ts
  src/module/gift/dataloader/gift.dataloader.ts
  src/module/gift/gift.module.ts
  src/module/item/controller/item.resolver.ts
  src/module/item/dataloader/item.dataloader.ts
  src/module/item/item.module.ts
  src/module/user/controller/user-mutation.resolver.ts
  src/module/user/controller/user-query.resolver.ts
  src/module/user/controller/user.resolver.ts
  src/module/user/dataloader/user-gift-histories.dataloader.ts
  src/module/user/dataloader/user.dataloader.ts
  src/module/user/user.module.ts
  yarn.lock
Labels: ✨新機能

#184 feat: ✨ 排出されたItemが未所持のItemであればリレーションテーブルに追加する処理を追加
  src/module/user/controller/dto/input/user-create.input.ts
  src/module/user/domain/service/repository/user.repository.ts
  src/module/user/repository/mocked-user.repository.ts
  src/module/user/repository/user.repository.spec.ts
  src/module/user/repository/user.repository.ts
  src/module/user/use-case/user-creator.use-case.ts
  src/module/user/use-case/user-gacha-manager.use-case.ts
Labels: ✨新機能

#185 feat: ✨ (UserUpdaterUseCase.incrementPoint) ポイント加算時にユーザーをゲームから退出させる処理を追加
  src/module/user/use-case/user-updater.use-case.ts
Labels: ✨新機能

#192 refactor: ♻️ 日付処理の部分をDateModuleに置換
  package.json
  src/app/app.module.ts
  src/common/date/date.module.ts
  src/common/date/date.service.ts
  src/module/user/controller/user-mutation.resolver.ts
  yarn.lock
Labels: ✨新機能, ♻リファクタリング

#193 feat: ✨ (UserMutation) Userのデータ変更時にFirebase Authenticationのデータにも変更を反映する処理を追加
  src/module/user/controller/user-mutation.resolver.ts
Labels: ✨新機能

#194 feat: ✨ getObtainmentStatuses GraphQL Queryを作成
  src/module/user/controller/dto/args/get-obtainment-statuses.args.ts
  src/module/user/controller/dto/object/obtainment-status.object.ts
  src/module/user/controller/user-query.resolver.ts
  src/module/user/domain/model/obtainment-status.model.ts
  src/module/user/domain/service/use-case/user-reader.use-case.ts
  src/module/user/use-case/user-reader.use-case.spec.ts
  src/module/user/use-case/user-reader.use-case.ts
Labels: ✨新機能

#189 refactor: ♻️ (user) incrementPointをUserGameManagerUseCaseに移動
  src/module/user/controller/user-mutation.resolver.ts
  src/module/user/domain/service/use-case/user-game-manager.use-case.ts
  src/module/user/domain/service/use-case/user-updater.use-case.ts
  src/module/user/use-case/user-game-manager.use-case.spec.ts
  src/module/user/use-case/user-game-manager.use-case.ts
  src/module/user/use-case/user-updater.use-case.spec.ts
  src/module/user/use-case/user-updater.use-case.ts
Labels: ♻リファクタリング

#195 feat: ✨ updatedGameAttenders GraphQL Subscriptionを作成
  src/common/constant/injection-token.constant.ts
  src/common/constant/pubsub-iterator.constant.ts
  src/module/user/controller/user-mutation.resolver.ts
  src/module/user/controller/user-subscription.resolver.ts
  src/module/user/domain/model/game-attenders.model.ts
  src/module/user/domain/service/use-case/user-publisher.ues-case.ts
  src/module/user/use-case/user-publisher.ues-case.spec.ts
  src/module/user/use-case/user-publisher.ues-case.ts
Labels: ✨新機能, 🧪テスト

#187 feat: ⚰️ (repository/use-case) 不要な/.*ById/メソッドを削除
  src/common/constant/injection-token.constant.ts
  src/module/gift-history/domain/service/repository/gift-history.repository.ts
  src/module/gift-history/domain/service/use-case/gift-history-reader.use-case.ts
  src/module/gift-history/repository/gift-history.repository.spec.ts
  src/module/gift-history/repository/gift-history.repository.ts
  src/module/gift-history/repository/mocked-gift-history.repository.ts
  src/module/gift-history/use-case/gift-history-reader.use-case.spec.ts
  src/module/gift-history/use-case/gift-history-reader.use-case.ts
  src/module/gift/domain/service/repository/gift.repository.ts
  src/module/gift/domain/service/use-case/gift-reader.use-case.ts
  src/module/gift/repository/gift.repository.spec.ts
  src/module/gift/repository/gift.repository.ts
  src/module/gift/repository/mocked-gift.repository.ts
  src/module/gift/use-case/gift-reader.use-case.spec.ts
  src/module/gift/use-case/gift-reader.use-case.ts
  src/module/item/domain/service/repository/item.repository.ts
  src/module/item/domain/service/use-case/item-reader.use-case.ts
  src/module/item/item.module.ts
  src/module/item/repository/item.repository.spec.ts
  src/module/item/repository/item.repository.ts
  src/module/item/repository/mocked-item.repository.ts
  src/module/item/use-case/item-reader.use-case.spec.ts
  src/module/item/use-case/item-reader.use-case.ts
  src/module/user/domain/service/repository/user.repository.ts
  src/module/user/domain/service/use-case/user-reader.use-case.ts
  src/module/user/repository/mocked-user.repository.ts
  src/module/user/repository/user.repository.spec.ts
  src/module/user/repository/user.repository.ts
  src/module/user/use-case/user-reader.use-case.spec.ts
  src/module/user/use-case/user-reader.use-case.ts
Labels: ♻リファクタリング, ⚰機能削除

#197 feat: ✨ InputPortを作成
  src/module/gift-history/controller/gift-history-mutation.resolver.ts
  src/module/gift-history/controller/gift-history-query.resolver.ts
  src/module/gift-history/domain/service/use-case/gift-history-creator.use-case.ts
  src/module/gift-history/domain/service/use-case/gift-history-reader.use-case.ts
  src/module/gift-history/domain/service/use-case/gift-history-updater.use-case.ts
  src/module/gift-history/domain/service/use-case/port/gift-history-creator.input.ts
  src/module/gift-history/domain/service/use-case/port/gift-history-reader.input.ts
  src/module/gift-history/domain/service/use-case/port/gift-history-updater.input.ts
  src/module/gift-history/use-case/gift-history-creator.use-case.spec.ts
  src/module/gift-history/use-case/gift-history-creator.use-case.ts
  src/module/gift-history/use-case/gift-history-reader.use-case.spec.ts
  src/module/gift-history/use-case/gift-history-reader.use-case.ts
  src/module/gift-history/use-case/gift-history-updater.use-case.spec.ts
  src/module/gift-history/use-case/gift-history-updater.use-case.ts
  src/module/gift/controller/gift-query.resolver.ts
  src/module/gift/domain/service/use-case/gift-reader.use-case.ts
  src/module/gift/domain/service/use-case/port/gift-reader.input.ts
  src/module/gift/use-case/gift-reader.use-case.spec.ts
  src/module/gift/use-case/gift-reader.use-case.ts
  src/module/user/controller/user-mutation.resolver.ts
  src/module/user/controller/user-query.resolver.ts
  src/module/user/controller/user-subscription.resolver.ts
  src/module/user/domain/service/use-case/port/user-creator.input.ts
  src/module/user/domain/service/use-case/port/user-game-manager.input.ts
  src/module/user/domain/service/use-case/port/user-reader.input.ts
  src/module/user/domain/service/use-case/port/user-updater.input.ts
  src/module/user/domain/service/use-case/user-creator.use-case.ts
  src/module/user/domain/service/use-case/user-gacha-manager.use-case.ts
  src/module/user/domain/service/use-case/user-game-manager.use-case.ts
  src/module/user/domain/service/use-case/user-reader.use-case.ts
  src/module/user/domain/service/use-case/user-updater.use-case.ts
  src/module/user/use-case/user-creator.use-case.spec.ts
  src/module/user/use-case/user-creator.use-case.ts
  src/module/user/use-case/user-gacha-manager.use-case.spec.ts
  src/module/user/use-case/user-gacha-manager.use-case.ts
  src/module/user/use-case/user-game-manager.use-case.spec.ts
  src/module/user/use-case/user-game-manager.use-case.ts
  src/module/user/use-case/user-reader.use-case.spec.ts
  src/module/user/use-case/user-reader.use-case.ts
  src/module/user/use-case/user-updater.use-case.spec.ts
  src/module/user/use-case/user-updater.use-case.ts
  src/module/user/user.module.ts
Labels: ♻リファクタリング

#198 fix: 🐞 レスポンスオブジェクトをロギングしないように修正
  src/cache/dataloader-cache.service.ts
  src/common/date/date.service.ts
  src/config/env/env.service.ts
  src/infra/firebase/firebase.service.ts
  src/infra/prisma/prisma.service.ts
  src/infra/pubsub/pubsub.service.ts
  src/module/gift-history/controller/gift-history-mutation.resolver.ts
  src/module/gift-history/controller/gift-history-query.resolver.ts
  src/module/gift/controller/gift-query.resolver.ts
  src/module/user/controller/user-mutation.resolver.ts
  src/module/user/controller/user-query.resolver.ts
Labels: 🐛バグ

#201 refactor: ♻️ @/common配下のファイルを整理
  src/app/app.module.ts
  src/common/base/dataloader/base.dataloader.ts
  src/common/base/repository/base.repository.ts
  src/guard/auth.guard.ts
  src/guard/role.guard.ts
  src/guard/util/get-id-by-auth-token.util.ts
  src/infra/date/date.module.ts
  src/infra/date/date.service.ts
  src/module/gift-history/controller/gift-history-mutation.resolver.ts
  src/module/gift-history/domain/service/repository/gift-history.repository.ts
  src/module/gift/dataloader/gift-gift-histories.dataloader.ts
  src/module/gift/dataloader/gift.dataloader.ts
  src/module/gift/domain/service/repository/gift.repository.ts
  src/module/item/dataloader/item.dataloader.ts
  src/module/item/domain/service/repository/item.repository.ts
  src/module/user/controller/user-mutation.resolver.ts
  src/module/user/dataloader/user-gift-histories.dataloader.ts
  src/module/user/dataloader/user.dataloader.ts
  src/module/user/domain/service/repository/user.repository.ts
Labels: ♻リファクタリング

#202 feat: ✨ (UserCreatorUseCase.createUser) キャラクターごとに自動でUrlを割り振るように修正
  .github/workflows/test.yml
  src/config/env/env.service.ts
  src/config/env/util/validator.util.ts
  src/module/user/controller/dto/input/user-create.input.ts
  src/module/user/domain/service/use-case/port/user-creator.input.ts
  src/module/user/use-case/user-creator.use-case.spec.ts
  src/module/user/use-case/user-creator.use-case.ts
Labels: ✨新機能

#205 ci: 🦺 (publish-graph) FIREBASE_STORAGE_URLを参照するように修正
  .github/workflows/publish-graph.yml
Labels: 🐛バグ, 🦺CI
