Repository 3I-shikosai32/shikosai32-server, pull requests merged in 2022-10, with the labels that each got.

#211 fix: 🐛 (GiftHistoryResolver) 期待されないGiftHistory.giftフィールドを削除
  src/module/gift-history/controller/gift-history.resolver.ts
Labels: 🐛バグ

#213 feat: ✨ CharacterStatusのField Resolverを作成
  src/module/character-status/character-status.module.ts
  src/module/character-status/controller/character-status.resolver.ts
  src/module/user/controller/dto/object/user.object.ts
  src/module/user/controller/user.resolver.ts
  src/module/user/dataloader/user-character-status.dataloader.ts
  src/module/user/user.module.ts
Labels: ✨新機能

#230 fix: 🚑️ (LICENSE.md) 著作権表記にサマーウォーズのOZに関する記述を追加した。
  LICENSE.md
Labels: 🚑重大な問題

#232 feat: ✨ (PrismaService) NODE_ENVがtestの場合Prismaのquery logを除外するように修正
  src/infra/prisma/prisma.service.ts
Labels: ✨新機能

#236 feat: ✨ findItemCompletedCharacterStatuses GraphQL Queryを作成
  src/common/constant/injection-token.constant.ts
  src/module/character-status/character-status.module.ts
  src/module/character-status/controller/character-status-query.resolver.ts
  src/module/character-status/controller/dto/args/find-item-completed-character-statuses.args.ts
  src/module/character-status/controller/dto/input/character-status-order.input.ts
  src/module/character-status/controller/dto/input/character-status-where-unique.ts
  src/module/character-status/controller/dto/input/character-status-where.input.ts
  src/module/character-status/controller/dto/input/item-completed-history-order.input.ts
  src/module/character-status/domain/service/repository/character-status.repository.ts
  src/module/character-status/domain/service/use-case/character-status-reader.use-case.ts
  src/module/character-status/domain/service/use-case/port/character-status-reader.input.ts
  src/module/character-status/repository/mocked-character-status.repository.ts
  src/module/character-status/use-case/character-status-reader.use-case.spec.ts
  src/module/character-status/use-case/character-status-reader.use-case.ts
  src/module/user/use-case/user-gacha-manager.use-case.spec.ts
  src/module/user/use-case/user-game-manager.use-case.spec.ts
  src/module/user/use-case/user-reader.use-case.spec.ts
Labels: ✨新機能, 🧪テスト

#237 fix: 🐞 (UserPublisherUseCase) pubSubRepositoryをpubSubServiceに改名
  src/module/user/use-case/user-publisher.ues-case.ts
Labels: 🐛バグ

#238 fix: 🐞 Prisma Schemaの問題を修正
  src/infra/prisma/generated/gift/gift-count-aggregate/input.ts
  src/infra/prisma/generated/gift/gift-count-aggregate/output.ts
  src/infra/prisma/generated/gift/gift-count-order-by-aggregate/input.ts
  src/infra/prisma/generated/gift/gift-create-many/input.ts
  src/infra/prisma/generated/gift/gift-create-without-gift-histories/input.ts
  src/infra/prisma/generated/gift/gift-create/input.ts
  src/infra/prisma/generated/gift/gift-group-by/output.ts
  src/infra/prisma/generated/gift/gift-max-aggregate/input.ts
  src/infra/prisma/generated/gift/gift-max-aggregate/output.ts
  src/infra/prisma/generated/gift/gift-max-order-by-aggregate/input.ts
  src/infra/prisma/generated/gift/gift-min-aggregate/input.ts
  src/infra/prisma/generated/gift/gift-min-aggregate/output.ts
  src/infra/prisma/generated/gift/gift-min-order-by-aggregate/input.ts
  src/infra/prisma/generated/gift/gift-order-by-with-aggregation/input.ts
  src/infra/prisma/generated/gift/gift-order-by-with-relation/input.ts
  src/infra/prisma/generated/gift/gift-scalar-field/enum.ts
  src/infra/prisma/generated/gift/gift-scalar-where-with-aggregates/input.ts
  src/infra/prisma/generated/gift/gift-unchecked-create-without-gift-histories/input.ts
  src/infra/prisma/generated/gift/gift-unchecked-create/input.ts
  src/infra/prisma/generated/gift/gift-unchecked-update-many/input.ts
  src/infra/prisma/generated/gift/gift-unchecked-update-without-gift-histories/input.ts
  src/infra/prisma/generated/gift/gift-unchecked-update/input.ts
  src/infra/prisma/generated/gift/gift-update-many-mutation/input.ts
  src/infra/prisma/generated/gift/gift-update-without-gift-histories/input.ts
  src/infra/prisma/generated/gift/gift-update/input.ts
  src/infra/prisma/generated/gift/gift-where/input.ts
  src/infra/prisma/generated/gift/gift/model.ts
  src/infra/prisma/generated/user/user-where-unique/input.ts
  src/infra/prisma/schema.prisma
  src/module/gift/controller/dto/object/gift.object.ts
  src/module/gift/domain/model/gift.model.ts
  src/module/gift/domain/service/use-case/port/gift-reader.input.ts
Labels: ✨新機能, ⚰機能削除

#242 feat: ✨ 特定条件下でItemCompletedHistoryを作成する処理を追加
  src/module/character-status/domain/model/character-status.model.ts
  src/module/character-status/repository/character-status.repository.ts
  src/module/user/domain/model/user.model.ts
  src/module/user/use-case/user-gacha-manager.use-case.ts
Labels: ✨新機能

#244 feat: ✨ (GraphQLConfigModule) validationRulesにcomplexityLimitを追加
  package.json
  src/config/graphql/graphql-config.module.ts
  yarn.lock
Labels: ✨新機能, 🚑重大な問題

#249 feat: ✨ updatedRanking GraphQL Subscriptionを作成
  src/common/constant/pubsub-iterator.constant.ts
  src/module/character-status/character-status.module.ts
  src/module/character-status/domain/service/repository/character-status.repository.ts
  src/module/character-status/domain/service/use-case/character-status-reader.use-case.ts
  src/module/character-status/repository/character-status.repository.spec.ts
  src/module/character-status/repository/character-status.repository.ts
  src/module/character-status/repository/mocked-character-status.repository.ts
  src/module/character-status/use-case/character-status-reader.use-case.spec.ts
  src/module/character-status/use-case/character-status-reader.use-case.ts
  src/module/user/controller/dto/args/updated-ranking.args.ts
  src/module/user/controller/dto/enum/ranking-target.enum.ts
  src/module/user/controller/user-mutation.resolver.ts
  src/module/user/controller/user-subscription.resolver.ts
  src/module/user/domain/service/repository/user.repository.ts
  src/module/user/domain/service/use-case/user-publisher.ues-case.ts
  src/module/user/use-case/user-publisher.ues-case.spec.ts
  src/module/user/use-case/user-publisher.ues-case.ts
Labels: ✨新機能, 🧪テスト

#251 fix: 🐞 update系のGraphQL Mutationを改名
  src/common/constant/injection-token.constant.ts
  src/module/gift-history/controller/dto/args/change-delivery-state-gift-history.args.ts
  src/module/gift-history/controller/dto/args/update-gift-history.args.ts
  src/module/gift-history/controller/dto/input/gift-history-change-delivery-state.input.ts
  src/module/gift-history/controller/gift-history-mutation.resolver.ts
  src/module/gift-history/domain/service/use-case/gift-history-delivery-manager.use-case.ts
  src/module/gift-history/domain/service/use-case/gift-history-updater.use-case.ts
  src/module/gift-history/gift-history.module.ts
  src/module/gift-history/use-case/gift-history-delivery-manager.use-case.spec.ts
  src/module/gift-history/use-case/gift-history-delivery-manager.use-case.ts
  src/module/user/controller/dto/args/update-user-bio.args.ts
  src/module/user/controller/dto/input/user-update-bio.input.ts
  src/module/user/controller/user-mutation.resolver.ts
  src/module/user/domain/service/use-case/port/user-updater.input.ts
  src/module/user/domain/service/use-case/user-updater.use-case.ts
  src/module/user/use-case/user-updater.use-case.spec.ts
  src/module/user/use-case/user-updater.use-case.ts
Labels: ♻リファクタリング

#241 feat: ✨ changeDeliveryStateCharacterStatus GraphQL Mutationを作成
  src/common/constant/injection-token.constant.ts
  src/module/character-status/character-status.module.ts
  src/module/character-status/controller/character-status-mutation.resolver.ts
  src/module/character-status/controller/character-status-query.resolver.ts
  src/module/character-status/controller/dto/args/change-delivery-state-character-status.args.ts
  src/module/character-status/domain/service/use-case/character-status-delivery-manager.use-case.ts
  src/module/character-status/use-case/character-status-delivery-manager.use-case.spec.ts
  src/module/character-status/use-case/character-status-delivery-manager.use-case.ts
Labels: ✨新機能, 🧪テスト

#254 fix: 🐞 User.CharacterStatusesをUser.characterStatusesに修正
  src/infra/prisma/generated/user/user-count/output.ts
  src/infra/prisma/generated/user/user-create-without-gift-histories/input.ts
  src/infra/prisma/generated/user/user-create/input.ts
  src/infra/prisma/generated/user/user-order-by-with-relation/input.ts
  src/infra/prisma/generated/user/user-unchecked-create-without-gift-histories/input.ts
  src/infra/prisma/generated/user/user-unchecked-create/input.ts
  src/infra/prisma/generated/user/user-unchecked-update-without-gift-histories/input.ts
  src/infra/prisma/generated/user/user-unchecked-update/input.ts
  src/infra/prisma/generated/user/user-update-without-gift-histories/input.ts
  src/infra/prisma/generated/user/user-update/input.ts
  src/infra/prisma/generated/user/user-where/input.ts
  src/infra/prisma/generated/user/user/model.ts
  src/infra/prisma/schema.prisma
  src/module/user/repository/user.repository.ts
  src/module/user/use-case/user-creator.use-case.ts
Labels: ♻リファクタリング

#253 fix: 🐞 (user/controller) UseCaseの変数にuser接頭辞を追加
  src/module/user/controller/user-mutation.resolver.ts
  src/module/user/controller/user-query.resolver.ts
Labels: ♻リファクタリング

#257 chore: 🔧 (github) release noteのテンプレートを作成
  .github/release.yml
Labels: 🛠設定

#259 refactor: ♻️ (github/release) 不要なchangelog.exclude.authorsを削除
  .github/release.yml
Labels: ♻リファクタリング

#262 feat: ✨ Item.urlを廃止し、Item.iconUrl及びItem.layerUrlを追加
  src/infra/prisma/generated/item/item-count-aggregate/input.ts
  src/infra/prisma/generated/item/item-count-aggregate/output.ts
  src/infra/prisma/generated/item/item-count-order-by-aggregate/input.ts
  src/infra/prisma/generated/item/item-create-many/input.ts
  src/infra/prisma/generated/item/item-create-without-character-statuses/input.ts
  src/infra/prisma/generated/item/item-create/input.ts
  src/infra/prisma/generated/item/item-group-by/output.ts
  src/infra/prisma/generated/item/item-max-aggregate/input.ts
  src/infra/prisma/generated/item/item-max-aggregate/output.ts
  src/infra/prisma/generated/item/item-max-order-by-aggregate/input.ts
  src/infra/prisma/generated/item/item-min-aggregate/input.ts
  src/infra/prisma/generated/item/item-min-aggregate/output.ts
  src/infra/prisma/generated/item/item-min-order-by-aggregate/input.ts
  src/infra/prisma/generated/item/item-order-by-with-aggregation/input.ts
  src/infra/prisma/generated/item/item-order-by-with-relation/input.ts
  src/infra/prisma/generated/item/item-scalar-field/enum.ts
  src/infra/prisma/generated/item/item-scalar-where-with-aggregates/input.ts
  src/infra/prisma/generated/item/item-scalar-where/input.ts
  src/infra/prisma/generated/item/item-unchecked-create-without-character-statuses/input.ts
  src/infra/prisma/generated/item/item-unchecked-create/input.ts
  src/infra/prisma/generated/item/item-unchecked-update-many-without-items/input.ts
  src/infra/prisma/generated/item/item-unchecked-update-many/input.ts
  src/infra/prisma/generated/item/item-unchecked-update-without-character-statuses/input.ts
  src/infra/prisma/generated/item/item-unchecked-update/input.ts
  src/infra/prisma/generated/item/item-update-many-mutation/input.ts
  src/infra/prisma/generated/item/item-update-without-character-statuses/input.ts
  src/infra/prisma/generated/item/item-update/input.ts
  src/infra/prisma/generated/item/item-where/input.ts
  src/infra/prisma/generated/item/item/model.ts
  src/infra/prisma/schema.prisma
  src/module/item/controller/dto/input/item-where.input.ts
  src/module/item/controller/dto/object/item.object.ts
  src/module/item/domain/model/item.model.ts
  src/module/item/repository/item.repository.spec.ts
  src/module/item/repository/mocked-item.repository.ts
  src/module/user/repository/mocked-user.repository.ts
Labels: ✨新機能

#266 fix: 🐞 (user/dto) GameAttendersのフィールド名をcamelCaseに修正
  src/module/user/controller/dto/object/game-attenders.object.ts
Labels: 🐛バグ

#269 fix: 🐛 Number GraphQL Scalar型のフィールドをInt GraphQL Scalar型に修正
  src/module/gift-history/controller/dto/args/exchange-gift.args.ts
  src/module/user/controller/dto/input/user-increment-point.input.ts
Labels: 🐛バグ

#265 feat: ✨ seedを実行するためのスクリプトを追加
  package.json
  src/infra/prisma/seed/main.seed.ts
  src/infra/prisma/seed/seeder/character-status.seeder.ts
  src/infra/prisma/seed/seeder/gift-history.seeder.ts
  src/infra/prisma/seed/seeder/gift.seeder.ts
  src/infra/prisma/seed/seeder/item.seeder.ts
  src/infra/prisma/seed/seeder/user.seeder.ts
Labels: ✨新機能, 🛠設定

#270 fix: 🐞 (prisma) 各userIdフィールドに@db.ObjectIdを追加
  src/infra/prisma/schema.prisma
Labels: 🐛バグ

#272 fix: 🐛 (GiftHistoryCreatorUseCase.exchangeGift) `create()`を`Promise.all()`で実行していた箇所を`createMany()`に置換
  src/module/gift-history/domain/service/repository/gift-history.repository.ts
  src/module/gift-history/repository/gift-history.repository.spec.ts
  src/module/gift-history/repository/gift-history.repository.ts
  src/module/gift-history/repository/mocked-gift-history.repository.ts
  src/module/gift-history/use-case/gift-history-creator.use-case.ts
Labels: 🐛バグ, ♻リファクタリング

#274 fix: 🐛 正しくrankingをpublishできない問題を修正
  src/common/constant/pubsub-iterator.constant.ts
  src/module/user/controller/dto/args/updated-ranking.args.ts
  src/module/user/controller/dto/enum/date.enum.ts
  src/module/user/controller/user-mutation.resolver.ts
  src/module/user/controller/user-subscription.resolver.ts
  src/module/user/use-case/user-publisher.ues-case.ts
Labels: 🐛バグ

#276 feat: ✨ Subscriptionの初期値を取得するためのQueryを作成
  src/module/user/controller/user-query.resolver.ts
  src/module/user/domain/service/use-case/user-reader.use-case.ts
  src/module/user/use-case/user-reader.use-case.spec.ts
  src/module/user/use-case/user-reader.use-case.ts
Labels: ✨新機能, 🧪テスト

#280 fix: 🐛 GameAttendersのdomain modelとGraphQL Objectの齟齬を修正
  src/module/user/domain/model/game-attenders.model.ts
  src/module/user/use-case/user-publisher.ues-case.ts
  src/module/user/use-case/user-reader.use-case.ts
Labels: 🐛バグ

#279 feat: ✨ getRankingPosition GraphQL Queryを作成
  src/module/user/controller/dto/args/get-ranking-position.args.ts
  src/module/user/controller/user-query.resolver.ts
  src/module/user/domain/service/use-case/user-reader.use-case.ts
  src/module/user/use-case/user-publisher.ues-case.spec.ts
  src/module/user/use-case/user-publisher.ues-case.ts
  src/module/user/use-case/user-reader.use-case.spec.ts
  src/module/user/use-case/user-reader.use-case.ts
Labels: ✨新機能

#283 fix: 🐛 (UserCreatorUseCase) Invalid this.prismaService.user.create()エラーが発生する問題を修正
  src/module/user/use-case/user-creator.use-case.ts
Labels: 🐛バグ

#286 feat: ✨ Ranking domain modelを作成
  src/module/user/controller/dto/object/ranking.object.ts
  src/module/user/controller/user-mutation.resolver.ts
  src/module/user/controller/user-query.resolver.ts
  src/module/user/controller/user-subscription.resolver.ts
  src/module/user/domain/model/ranking.model.ts
  src/module/user/domain/service/use-case/user-publisher.ues-case.ts
  src/module/user/domain/service/use-case/user-reader.use-case.ts
  src/module/user/use-case/user-publisher.ues-case.spec.ts
  src/module/user/use-case/user-publisher.ues-case.ts
  src/module/user/use-case/user-reader.use-case.spec.ts
  src/module/user/use-case/user-reader.use-case.ts
Labels: ✨新機能

#290 fix: 🚑️ (GraphQLConfigModule) 複雑度閾値を5000に修正
  src/config/graphql/graphql-config.module.ts
Labels: 🐛バグ, 🚑重大な問題

#288 fix: 🚑️ User.idに指定したidを格納できない問題を修正
  package.json
  src/infra/prisma/generated/user/user-create-many/input.ts
  src/infra/prisma/generated/user/user-create-without-character-statuses/input.ts
  src/infra/prisma/generated/user/user-create-without-gift-histories/input.ts
  src/infra/prisma/generated/user/user-create/input.ts
  src/infra/prisma/generated/user/user-unchecked-create-without-character-statuses/input.ts
  src/infra/prisma/generated/user/user-unchecked-create-without-gift-histories/input.ts
  src/infra/prisma/generated/user/user-unchecked-create/input.ts
  src/infra/prisma/schema.prisma
  src/infra/prisma/seed/seeder/user.seeder.ts
  src/module/user/repository/user.repository.spec.ts
  yarn.lock
Labels: 🐛バグ, 🚑重大な問題

#295 feat: ✨ User modelに`authId`を追加
  src/common/constant/injection-token.constant.ts
  src/infra/prisma/generated/user/user-count-aggregate/input.ts
  src/infra/prisma/generated/user/user-count-aggregate/output.ts
  src/infra/prisma/generated/user/user-count-order-by-aggregate/input.ts
  src/infra/prisma/generated/user/user-create-many/input.ts
  src/infra/prisma/generated/user/user-create-without-character-statuses/input.ts
  src/infra/prisma/generated/user/user-create-without-gift-histories/input.ts
  src/infra/prisma/generated/user/user-create/input.ts
  src/infra/prisma/generated/user/user-group-by/output.ts
  src/infra/prisma/generated/user/user-max-aggregate/input.ts
  src/infra/prisma/generated/user/user-max-aggregate/output.ts
  src/infra/prisma/generated/user/user-max-order-by-aggregate/input.ts
  src/infra/prisma/generated/user/user-min-aggregate/input.ts
  src/infra/prisma/generated/user/user-min-aggregate/output.ts
  src/infra/prisma/generated/user/user-min-order-by-aggregate/input.ts
  src/infra/prisma/generated/user/user-order-by-with-aggregation/input.ts
  src/infra/prisma/generated/user/user-order-by-with-relation/input.ts
  src/infra/prisma/generated/user/user-scalar-field/enum.ts
  src/infra/prisma/generated/user/user-scalar-where-with-aggregates/input.ts
  src/infra/prisma/generated/user/user-unchecked-create-without-character-statuses/input.ts
  src/infra/prisma/generated/user/user-unchecked-create-without-gift-histories/input.ts
  src/infra/prisma/generated/user/user-unchecked-create/input.ts
  src/infra/prisma/generated/user/user-unchecked-update-many/input.ts
  src/infra/prisma/generated/user/user-unchecked-update-without-character-statuses/input.ts
  src/infra/prisma/generated/user/user-unchecked-update-without-gift-histories/input.ts
  src/infra/prisma/generated/user/user-unchecked-update/input.ts
  src/infra/prisma/generated/user/user-update-many-mutation/input.ts
  src/infra/prisma/generated/user/user-update-without-character-statuses/input.ts
  src/infra/prisma/generated/user/user-update-without-gift-histories/input.ts
  src/infra/prisma/generated/user/user-update/input.ts
  src/infra/prisma/generated/user/user-where-unique/input.ts
  src/infra/prisma/generated/user/user-where/input.ts
  src/infra/prisma/generated/user/user/model.ts
  src/infra/prisma/schema.prisma
  src/infra/prisma/seed/seeder/user.seeder.ts
  src/module/character-status/repository/mocked-character-status.repository.ts
  src/module/user/controller/dto/args/find-user.args.ts
  src/module/user/controller/dto/args/get-obtainment-statuses.args.ts
  src/module/user/controller/dto/args/get-ranking-position.args.ts
  src/module/user/controller/dto/args/join-game.args.ts
  src/module/user/controller/dto/args/pull-gacha.args.ts
  src/module/user/controller/dto/args/update-user-bio.args.ts
  src/module/user/controller/dto/input/user-create.input.ts
  src/module/user/controller/dto/input/user-where-unique-auth-id.input.ts
  src/module/user/controller/dto/input/user-where.input.ts
  src/module/user/controller/dto/object/user.object.ts
  src/module/user/controller/user-mutation.resolver.ts
  src/module/user/controller/user-query.resolver.ts
  src/module/user/domain/model/user.model.ts
  src/module/user/domain/service/use-case/port/user-creator.input.ts
  src/module/user/domain/service/use-case/port/user-updater.input.ts
  src/module/user/domain/service/use-case/user-updater.use-case.ts
  src/module/user/repository/mocked-user.repository.ts
  src/module/user/repository/user.repository.spec.ts
  src/module/user/use-case/user-creator.use-case.ts
  src/module/user/use-case/user-updater.use-case.spec.ts
  src/module/user/use-case/user-updater.use-case.ts
  src/module/user/user.module.ts
Labels: ✨新機能

#296 refactor: ♻️ Date GraphQL EnumをRankingPeriodに改名
  src/common/constant/pubsub-iterator.constant.ts
  src/module/user/controller/dto/args/updated-ranking.args.ts
  src/module/user/controller/dto/enum/date.enum.ts
  src/module/user/controller/user-mutation.resolver.ts
  src/module/user/controller/user-query.resolver.ts
  src/module/user/domain/service/use-case/user-publisher.ues-case.ts
  src/module/user/domain/service/use-case/user-reader.use-case.ts
  src/module/user/use-case/user-publisher.ues-case.spec.ts
  src/module/user/use-case/user-publisher.ues-case.ts
  src/module/user/use-case/user-reader.use-case.spec.ts
  src/module/user/use-case/user-reader.use-case.ts
Labels: ♻リファクタリング

#298 fix: 🐛 (user/use-case) authIdで探索するべき箇所を修正
  src/module/user/use-case/user-gacha-manager.use-case.spec.ts
  src/module/user/use-case/user-gacha-manager.use-case.ts
  src/module/user/use-case/user-game-manager.use-case.spec.ts
  src/module/user/use-case/user-game-manager.use-case.ts
  src/module/user/use-case/user-reader.use-case.spec.ts
  src/module/user/use-case/user-reader.use-case.ts
Labels: 🐛バグ
